### ISSUE TITLE
What is deep_laboratory licensed under?

### ISSUE THREAD

**Issue by hiromi-mi** [hoppiece/deep_laboratory#1]
他のプロダクトから利用しやすくするために、ソフトウエアライセンスの方を明記することはできますでしょうか。
ライセンスの選び方および宣言方法については Free Software Foundation Europe による https://reuse.software/tutorial/ や GitHub による https://choosealicense.com/ などが参考になるかと思います。(可能でしたら Apache License や MIT License などのライセンスでしたら再利用が容易だとも思います。)

以上、ご検討のほどよろしくお願いします。

**Comment by hoppiece** [comment]
ありがとうございます. MIT Licence での配布を検討します.

**Comment by hoppiece** [comment]
https://github.com/hoppiece/deep_laboratory/pull/2 で MIT License を追加いたしました.

**Comment by hiromi-mi** [comment]
Thank you!
